import type { Business, Category } from "./types";

export const categories: Category[] = [
  { slug: "restaurants", name: { uk: "Ресторани", en: "Restaurants" } },
  { slug: "grocery-stores", name: { uk: "Їжа", en: "Food" } },
  { slug: "shops", name: { uk: "Магазин", en: "Shop" } },
  { slug: "lawyers", name: { uk: "Юридичні послуги", en: "Legal Services" } },
  { slug: "realtors", name: { uk: "Рієлтори", en: "Realtors" } },
  { slug: "moving", name: { uk: "Переїзд", en: "Moving" } },
  { slug: "insurance-brokers", name: { uk: "Страховий брокер", en: "Insurance Broker" } },
  { slug: "bookkeepers", name: { uk: "Бухгалтери", en: "Bookkeepers" } },
  { slug: "beauty", name: { uk: "Краса", en: "Beauty" } },
  { slug: "wellness-care", name: { uk: "Здоров'я та турбота", en: "Wellness & Care" } },
  { slug: "construction", name: { uk: "Будівництво", en: "Construction" } },
  { slug: "repair-services", name: { uk: "Ремонтні послуги", en: "Repair Services" } },
  { slug: "textile-decor", name: { uk: "Текстиль та декор", en: "Textiles & Decor" } },
  { slug: "cleaning", name: { uk: "Клінінг", en: "Cleaning" } },
  { slug: "auto-repair", name: { uk: "Автосервіс", en: "Auto Repair" } },
  { slug: "tutors", name: { uk: "Репетитори", en: "Tutors" } },
  { slug: "it-services", name: { uk: "IT-послуги", en: "IT Services" } },
  { slug: "flowers", name: { uk: "Квіти", en: "Flowers" } },
  { slug: "events", name: { uk: "Івенти", en: "Events" } },
  { slug: "travel-tours", name: { uk: "Подорожі та туризм", en: "Travel & Tours" } },
  { slug: "photographers", name: { uk: "Фото та відео", en: "Photo & Video" } },
  { slug: "advertising-services", name: { uk: "Рекламні послуги", en: "Advertising Services" } },
];

export const citySuggestions = [
  "Ottawa",
  "Stittsville",
  "Gatineau",
  "Toronto",
  "Mississauga",
  "Montreal",
  "Vancouver",
  "Calgary",
  "Edmonton",
  "Winnipeg",
  "Saskatoon",
  "Halifax",
  "St. John's",
];

export const businesses: Business[] = [
  {
    id: "kredance",
    name: "Kredance",
    categorySlug: "it-services",
    city: "Stittsville",
    ownerName: "Myroslav Vozniak",
    description: "IT and AI services for small businesses across Canada.",
    phone: "438-497-3894",
    website: "kredance.com",
    instagram: "itskredance",
    servesAllCanada: true,
    ownedByCurrentUser: true,
  },
  {
    id: "fefa-events",
    name: "FeFa Event Agency",
    categorySlug: "events",
    city: "Ottawa",
    ownerName: "FeFa Event Agency",
    description: "Event planning, decor, and celebration support in the capital region.",
    phone: "613-555-0184",
    website: "fefaevents.ca",
    servesAllCanada: false,
  },
  {
    id: "travel-client",
    name: "Maple Tryzub Travel",
    categorySlug: "travel-tours",
    city: "Toronto",
    ownerName: "Oksana Travel",
    description: "Vacation planning, tickets, tours, and Canada-wide trip support.",
    phone: "647-555-0198",
    website: "mapletryzubtravel.ca",
    servesAllCanada: true,
  },
  {
    id: "pinchuk-auto",
    name: "Pinchuk Auto Detailing",
    categorySlug: "auto-repair",
    city: "Ottawa",
    ownerName: "Виктор Пинчук",
    description: "Auto detailing, seasonal care, and maintenance in Ottawa.",
    phone: "343-997-3717",
    website: "",
    servesAllCanada: false,
  },
];
